# clowder server
version: '3.2'

services:

  # elasticsearch to allow indexing
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
    restart: always
    user: "1000:1258"
    environment:
      - cluster.name=skope
      - bootstrap.memory_lock=true
      - path.data=/state/esdata
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /projects/skope:/projects/skope
      - ./state:/state
    ports:
      - "9200:9200"
  
  # geoserver to render tiles
  geoserver:
    build: geoserver
    restart: always
    user: "1000:1258"
    environment:
      JAVA_OPTS: "-Xmx1536M -XX:MaxPermSize=756M -Duser.timezone=GMT -Dorg.geotools.shapefile.datetime=true"
      GEOSERVER_DATA_DIR: "/state/geoserver"
    volumes:
      - /projects/skope:/projects/skope
      - ./state:/state

  timeseries-service:
    image: openskope/timeseries-service:latest
    command: start
    restart: always
    user: "0:1258"
    environment:
      TIMESERIES_SERVICE_BASE: timeseries-service/api/v1
      TIMESERIES_DATA_PATH_TEMPLATE: /projects/skope/datasets/{datasetId}/{variableName}/cube.tif
      TIMESERIES_UNCERTAINTY_PATH_TEMPLATE: /projects/skope/datasets/{datasetId}/{variableName}/uncertainty.tif
      TIMESERIES_DATA_FILE_EXTENSIONS: .tif .nc4 .nc
      TIMESERIES_MAX_PROCESSING_TIME: 15000
    volumes:
      - /projects/skope:/projects/skope

  mongo:
    image: mongo:latest
    restart: always
    user: "1000:1258"
    command: "mongod --dbpath /state/mongo"
    ports:
      - "27017:27017"
    volumes:
      - /projects/skope:/projects/skope
      - ./state:/state

  webapp:
    image: openskope/webapp:latest
    restart: always
    volumes:
      - ./webapp/staging-settings.json:/usr/share/meteor-app/app-settings.json
    environment:
      MONGO_URL: "mongodb://mongo:27017/skope-webapp"
      ROOT_URL: "http://tacc-staging.openskope.org/app"
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch
      - mongo
      - web
  
  web:
    build: nginx
    restart: always
    user: "0:1258"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/cache/nginx:/var/lib/nginx/cache
      - /projects/skope:/projects/skope
    ports:
      - "80:80"
      - "443:443"

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1454

